apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaMirrorMaker
metadata:
  name: mirror-maker
spec:
  version: 2.3.0
  replicas: 1
  consumer:
    bootstrapServers: source-cluster-kafka-bootstrap:9092
    groupId: my-source-group-id
  producer:
    bootstrapServers: target-cluster-kafka-bootstrap:9092
  whitelist: ".*"