apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  labels:
    app: my-connect-cluster
spec:
  image: quay.io/scholzj/demo-kafka-and-its-friends-2019:kafka-connect-debezium-cdc
  version: 2.2.1
  replicas: 1
  resources:
    requests:
      memory: 2Gi
      cpu: 250m
    limits:
      memory: 2Gi
      cpu: 250m
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  jvmOptions:
    gcLoggingEnabled: false
  config:
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: my-connect-cluster
  labels:
    app: my-connect-cluster
spec:
  port:
    targetPort: rest-api
  to:
    kind: Service
    name: my-connect-cluster-connect-api
---
