apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: StrimziAdminBinding
subjects:
  - kind: User
    name: developer
roleRef:
  kind: ClusterRole
  name: StrimziAdmin
  apiGroup: rbac.authorization.k8s.io